version: '3.3'
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4.4
    ports:
      - 27017:27017/tcp
    volumes:
      - mongodb:/data/db
    networks:
      - otus-project

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11.2-alpine
    networks:
      - otus-project

  crawler:
    container_name: crawler
    hostname: crawler
    image: ${DOCKER_LOGIN}/search_engine_crawler:latest
    environment:
      - RMQ_HOST=rabbitmq
      - EXCLUDE_URLS=""
      - CHECK_INTERVAL=10
      - MONGO=mongodb
      - MONGO_PORT=27017
      - URL=http://info.cern.ch/
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - otus-project

  ui:
    container_name: ui
    hostname: ui
    image: ${DOCKER_LOGIN}/search_engine_ui:latest
    ports:
      - 8000:8000/tcp
    networks:
      - otus-project
    depends_on:
      - crawler

volumes:
  mongodb:

networks:
  otus-project:
    driver: bridge
    driver_opts:
      subnet: 10.0.1.0/24
