---
crawler:
  image:
    repository: cancer13/search_engine_crawler
    tag: ""
  service:
    port: 8000
  env:
    RMQ_HOST: ""
    EXCLUDE_URLS: ""
    CHECK_INTERVAL: "10"
    MONGO: ""
    MONGO_PORT: "27017"
    URL: "http://info.cern.ch/"

ui:
  image:
    repository: cancer13/search_engine_ui
    tag: ""
  service:
    type: ClusterIP
    port: 8000
  mongoHost: ""
  mongoPort: "27017"
  ingress:
    enabled: true
    className: nginx
    path: /
    host: 158.160.40.207.sslip.io
