---
app:
  image:
    repository: cancer13/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: cancer13/ui
    tag: latest
  service:
    externalPort: 8000
  ingress:
    path: /
    host: dev