# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cancer13/search_engine_ui
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  class: nginx
  path: /
  host: localhost
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}


mongoHost: "mongodb"
mongoPort: 27017
