apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: MONGO
            value: {{  .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
          - name: MONGO_PORT
            value: {{  .Values.mongoPort | default "27017" | quote }}
