apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler.fullname" . }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- end }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
      {{ end }}
      {{- if .Values.extraExposePorts }}
      {{- tpl (toYaml .Values.extraExposePorts) . | nindent 4 }}
      {{- end }}
  selector:
    {{- include "crawler.selectorLabels" . | nindent 4 }}
